server:
  port: 11000
spring:
  application:
     name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka.com:11000/eureka
    fetch-registry: false
    register-with-eureka: true
